# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opsy < Formula
  desc "Your AI-Powered SRE Colleague"
  homepage "https://github.com/datolabs-io/opsy"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datolabs-io/opsy/releases/download/v0.0.2/opsy_Darwin_x86_64.tar.gz"
      sha256 "ab3b4bbe0c6fc1ee551489aed0822fb688142443ed1037c8cabaaab1c6eeb955"

      def install
        bin.install "opsy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datolabs-io/opsy/releases/download/v0.0.2/opsy_Darwin_arm64.tar.gz"
      sha256 "e2445764f424be360d0c3462a402e2aee384e64d68634213b642373983d57a8e"

      def install
        bin.install "opsy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/datolabs-io/opsy/releases/download/v0.0.2/opsy_Linux_x86_64.tar.gz"
        sha256 "c3f0ed8587d91a29291f737e8069d8074605f6c582fb1a3588c5093b2029419f"

        def install
          bin.install "opsy"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/datolabs-io/opsy/releases/download/v0.0.2/opsy_Linux_armv6.tar.gz"
        sha256 "a05aff97bc95e9870cc561823f76e313873ee4404fcb6e31b879d8ba32af553a"

        def install
          bin.install "opsy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/datolabs-io/opsy/releases/download/v0.0.2/opsy_Linux_arm64.tar.gz"
        sha256 "52b85f8d365fb1029e5fbf0048619599a08902307d8523afc864666ebd9b77bd"

        def install
          bin.install "opsy"
        end
      end
    end
  end
end
