name: CI

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.vscode/**'
      - 'Formula/**'
      - '.gitattributes'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'README.md'
      - '.editorconfig'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.vscode/**'
      - 'Formula/**'
      - '.gitattributes'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'README.md'
      - '.editorconfig'
      - 'LICENSE'

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Build
      run: go build -v ./...

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Lint
      uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
      with:
        version: v2.4.0

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: go.mod
        cache: true
    - name: Test
      run: go test -v -covermode=atomic ./...
